config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  resources :comments
  resources :furnitures
  resources :users

  get 'home/index'
  get 'home/contact'
  get 'home/careers'
  get 'home/wishlist'
  get 'home/settings'
  get 'home/lottery'
  get 'home/lottery_gamble'
  get 'home/error'
  get 'home/wishlist'
  get '/by_category' => 'furnitures#by_category'
  

  delete '/logout' => 'sessions#logout'
  post '/login' => 'sessions#login'
  post '/signup' => 'sessions#signup'
  post '/purchase' => 'furnitures#purchase'
  post '/trade' => 'furnitures#trade'
  post '/add_wishlist' => 'home#add_wishlist'
  delete '/remove_wishlist' => 'home#remove_wishlist'

  get 'furnitures/wishlist'
  get 'home/wish'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index    
  end

#function to remove multiples from user_fav
#when joint table replaced by 12many, check for doubles in if sttemnt
  def add_wishlist
    puts 'insidez add_wishlist'
    relevant_furni = Furniture.find(params[:furniture_id])
    relevant_user = User.find(params[:user_id])
    puts relevant_user
    puts current_user
    puts relevant_furni
    if relevant_user == nil
      puts 'already wishlist'
      flash[:alert] = "You already added this item to your wishlist!"
      # redirect_to '/home/wishlist'
    else
      puts 'creating new wishlist'
      wishlist = Wishlist.create(furniture_id: relevant_furni.id, user_id: relevant_user.id)
      if wishlist.save
        @user_fav = Wishlist.where(user_id: session[:user_id])
        puts 'user_fav is'
        puts @user_fav
      else
        flash[:alert] = "Wishlist couldn't be saved"
      end
    end
    redirect_to '/home/wishlist'
  end

  #delete
  def remove_wishlist
    puts 'inside remove wishlist'
    curr_wish = params[:wishlist_id]
    rm_wish = Wishlist.find(params[:wishlist_id])
    puts rm_wish
    rm_wish.destroy
    redirect_to '/home/wishlist'
  end


  def wishlist
    if current_user == nil
      redirect_to '/home/error'
    else
      @user_fav = Wishlist.where(user_id: current_user.id)
      @fav_furnis = []
      if @user_fav.count > 1
        @first_id = @user_fav[0].id
      end
      @user_fav.each do |fav|
        furni = Furniture.find(fav.furniture_id)
        @fav_furnis << furni
      end
      @fav_furnis = @fav_furnis.uniq
      return @fav_furnis
    end   
  end  

  def settings
  	if current_user == nil
  		redirect_to '/home/error'
  	end
  end

  def lottery
    puts 'inside lottery'
    if current_user == nil
      redirect_to '/home/error'
    end    
  end

  def lottery_gamble
    puts 'inside lottery gamble'
    if current_user == nil
      redirect_to '/home/error'
    else
      curr_furni = current_user.furnipoints
      puts 'current furni'
      puts curr_furni
      furni_option = curr_furni + Random.rand(-50..50)
      current_user.update({furnipoints: furni_option - 10 })
      flash[:alert]= "Lottery completed. Check your new furnipoint count! :D"
      redirect_to "/home/lottery"
  	end  	
  end

  def error
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/careers.html.erb
<div class="contacts container">No jobs yet.</div>

app/views/home/contact.html.erb
<div class="contacts container">
	<h2 style="text-align: left;"> Contact </h2>
      <h6>samguergen@gmail.com</h6>
      <h6><a href="http://twitter.com/jusdepommes25">@jusdepommes25</a></h6>
      <h6><a href="https://github.com/samguergen">github.com/samguergen</a></h6>
      <h6><a href="https://bitbucket.org/samguergen">bitbucket.org/samguergen</a></h6>
      <h6><a href="http://www.linkedin.com/in/samanthaguergenenov">linkedin.com/in/samanthaguergenenov</a></h6>
</div>

app/views/home/error.html.erb
<div class="login-please">

Please log in or sign up to view this page 

<p class="smiley">¯\_(ツ)_/¯</p>

</div>	

app/views/home/index.html.erb
<div class="arrow">
  <%= image_tag("arrow.png", :alt => "arrow", :class => "arrow") %>
</div>
<div class="arrow-quote">
  Sign up to take advantage of the best features!
</div>

<%= image_tag("columns.png", :alt => "columns", :class => "columns") %>
<%= image_tag("columns.png", :alt => "columns2", :class => "columns2") %>

<header id="myCarousel" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for Slides -->
    <div class="carousel-inner">

       <div class="item active">
            <!-- Set the first background image using inline CSS below. -->
            <div class="fill" id="first-img"><%= image_tag("bedroom-ff.jpg", :alt => "bedroom", :class => "home-img") %></div>
            <div class="carousel-caption">
                <h1>Trade existing furniture with ones that fit your new room.</h1>
                <!-- <h1><em>Find the best new picks with Fitting Furniture!</em></h1> -->
                <a href="/furniture"><button style="margin-top:15px" class="btn btn-warning">Explore Furniture for sale, or trade at the FurniMarket!</button></a>
            </div>
        </div>

        <div class="item">
            <!-- Set the second background image using inline CSS below. -->
            <div class="fill" id="second-img"><%= image_tag("ebedroom-ff.jpg", :alt => "bedroom2", :class => "home-img") %></div>
            <div class="carousel-caption">
                <h1>Sell your furniture and purchase new ones with your furnipoints.</h1>
                <h1><em>If trade doesn't work, Fitting Furniture gives you the best alternatives.</em></h1>
            </div>
        </div>

        <div class="item">
            <!-- Set the third background image using inline CSS below. -->
            <div class="fill" id="third-img"><%= image_tag("living-ff.jpg", :alt => "living", :class => "home-img") %></div>
            <div class="carousel-caption">
                <h1>Create your ideal room, and make new friends!</h1>
                <h1><em>Fitting Furniture is a place for many things.</em></h1>
            </div>
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="icon-next"></span>
    </a>

</header>



<!-- 
<div class="jumbotron">
  <div class="container">
    <h1>Home#index</h1>
	<p>Find me in app/views/home/index.html.erb</p>
  </div>
</div>
<div class="jumbotron">
  <div class="container">
    <h1>Second jumbo</h1>
	<p>Second section of website</p>
  </div>
</div>

 -->

app/views/home/lottery.html.erb
<%= image_tag("columns.png", :alt => "columns", :class => "columns") %>
<%= image_tag("columns.png", :alt => "columns2", :class => "columns2") %>

<div class="lottery container">

To participate in this lottery, you must pay 10 furnipoints. </br>

To start, click on the link below: </br>

<%= link_to home_lottery_gamble_path do %>
   <%= image_tag "gamble.jpg", class: "gamble" %>
<% end %>

<div class="furni-count">You currently have: <%= current_user.furnipoints %> furnipoints.
</div>

</div>

app/views/home/settings.html.erb
<%= image_tag("columns.png", :alt => "columns", :class => "columns") %>
<%= image_tag("columns.png", :alt => "columns2", :class => "columns2") %>

<div class="settings">

<div class="setting-links">
	<a href="/users/<%= current_user.id %>/edit"><button class="btn btn-warning settings-edit">Edit Profile</button></a>

	<%= button_to "Delete Your Account", { :action=>"destroy", :controller=>"users", id: current_user.id }, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-warning settings-cancel"  %>

	<a href="/home/lottery"><button class="btn btn-warning settings-lottery">View Profile</button></a>
</div>

</div>

app/views/home/wish.html.erb
<div class="wishlist">

My wishlist:

count: <%= @user_fav %> <br>





</div>

app/views/home/wishlist.html.erb
<%= image_tag("columns.png", :alt => "columns", :class => "columns") %>
<%= image_tag("columns.png", :alt => "columns2", :class => "columns2") %>

<div class="wishlist container">
	<h2> Wishlist </h2>

	<div class="wishlist-imgs">
		<% @fav_furnis.each do |ufav| %> 
		<div class="wishlist-img">
			<a href="/furnitures/<%= ufav.id %>"><img src="<%= ufav.image_url %>"/></a>
		</div>
		<%= button_to "Remove", remove_wishlist_path, method: :delete, class: "btn-group btn-group-xs btn-wishlist btn-wishlist-rm", params: { wishlist_id: @first_id } %>
		<% end %>
	</div>
</div>