config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  resources :comments
  resources :furnitures
  resources :users

  get 'home/index'
  get 'home/contact'
  get 'home/careers'
  get 'home/wishlist'
  get 'home/settings'
  get 'home/lottery'
  get 'home/lottery_gamble'
  get 'home/error'
  get 'home/wishlist'
  get '/by_category' => 'furnitures#by_category'
  

  delete '/logout' => 'sessions#logout'
  post '/login' => 'sessions#login'
  post '/signup' => 'sessions#signup'
  post '/purchase' => 'furnitures#purchase'
  post '/trade' => 'furnitures#trade'
  post '/add_wishlist' => 'home#add_wishlist'
  delete '/remove_wishlist' => 'home#remove_wishlist'

  get 'furnitures/wishlist'
  get 'home/wish'

end

app/models/furniture.rb
class Furniture < ActiveRecord::Base
	belongs_to :user
	has_many :comments

	mount_uploader :image, ImageUploader
end

app/controllers/furnitures_controller.rb
class FurnituresController < ApplicationController
  before_action :set_furniture, only: [:show, :edit, :update, :destroy]

  def index
    @furnitures = Furniture.where(onsale: true)
    if session[:user_id]
      @current_user = User.find(session[:user_id])
      @current_furni = @current_user.furnitures
      @user_of_furnis = []
      @current_furni.each do |furni|
        @user_of_furnis << User.find(furni.user_id)
      end
    end
  end

  def show
    @furni = Furniture.find(params[:id])
    @comments = @furni.comments
  end

  def new
    @furniture = Furniture.new
  end

  def edit
  end

  # get
  def by_category
    @furniturez = Furniture.where(name: params[:type])
    render "category"
  end

  def trade
    # puts 'inside trade method'
    # puts 'the user is '
    # puts session[:user_id]
    current_user = User.find(session[:user_id])
    wanted_furni = Furniture.find(params[:furniId2])
    my_chosen_furni = Furniture.find(params[:furnichosen])
    user_of_furni = User.find(wanted_furni.user_id)
    
    #switching furni in current user
    wanted_furni.update(user_id: current_user.id, onsale: false)
    my_chosen_furni.update(user_id: user_of_furni.id, onsale: false)

    redirect_to '/furnitures'
  end

  # post
  def purchase
    #1-Adding furnipts to owner
    furni_id = params[:furniId]
    the_furni = Furniture.find(params[:furniId])
    the_user = User.find(the_furni.user_id)
    furnipts = the_user.furnipoints
    new_furnipts = furnipts + the_furni.furnipoints
    the_user.update(furnipoints: new_furnipts)

    #2-Subtracting furnipts from buyer
    curr_user = User.find(session[:user_id])
    curr_furnipts = curr_user.furnipoints
    curr_new_furnipts = curr_furnipts - the_furni.furnipoints
    curr_user.update(furnipoints: curr_new_furnipts)

    #3-transferring furni from owner to buyer
    the_furni.update(user_id: curr_user.id, onsale: false)

    redirect_to '/furnitures'
  end

  #post
  # def wishlist
  #   puts 'inside wishlist method'
  #   if session[:user_id]
  #     @favorite_furni = Furniture.find(params[:furniture_id])
  #     @favorite_furni.update(favoriter_id: current_user.id)
      
  #     puts 'user fav is'
  #     @user_fav
  #     redirect_to '/home/wishlist'
  #   else 
  #     redirect_to '/home/error'
  #   end
  # end

  def create
    @furniture = Furniture.new(furniture_params)

    respond_to do |format|
      if @furniture.save
        puts 'furnitcha was saved'
        format.html { redirect_to @furniture, notice: 'Furniture was successfully created.' }
        format.json { render :show, status: :created, location: @furniture }
      else
        format.html { render :new }
        format.json { render json: @furniture.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @furniture.update(furniture_params)
        format.html { redirect_to @furniture, notice: 'Furniture was successfully updated.' }
        format.json { render :show, status: :ok, location: @furniture }
      else
        format.html { render :edit }
        format.json { render json: @furniture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @furniture.destroy
    respond_to do |format|
      format.html { redirect_to furnitures_url, notice: 'Furniture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_furniture
      @furniture = Furniture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def furniture_params
      params.require(:furniture).permit(:name, :content, :image, :dimensions, :condition, :furnipoints).merge(user_id:session[:user_id])
    end
end

app/helpers/furnitures_helper.rb
module FurnituresHelper
end

app/views/furnitures/_form.html.erb
<div class="furni-form">
<%= form_for(@furniture) do |f| %>
  <% if @furniture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@furniture.errors.count, "error") %> prohibited this furniture from being saved:</h2>

      <ul>
      <% @furniture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="label">Furniture Type</div><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <div class="label">Description</div><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <div class="label"><%= f.label :dimensions %></div><br>
    <%= f.text_field :dimensions %>
  </div>
  <div class="field">
    <div class="label"><%= f.label :condition %></div><br>
    <%= f.text_field :condition %>
  </div>
  <div class="field">
    <div class="label"><%= f.label :cost %></div><br>
    <%= f.text_field :furnipoints %> furnipoints
  </div>
  <div class="field">
    <div class="label"><%= f.label :image %></div><br>
    <%= f.file_field :image %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/furnitures/category.html.erb
<div class="filtered-furni">
	<h2> Filtered for: <%= @furniturez.first.name %>s</h2>

    <a href="/furnitures"><button class="btn btn-warning back-btn">Back to furniture list</button></a>

    <% @furniturez.each do |furniture| %>

    <div class="furni-obj">
        <div class="furni-line1">
          <div class="furni-img">
            <a style="width:200px; height: 200px" href="/furnitures/<%= furniture.id %>">
            <img style="width:200px; height: 200px" src=<%= furniture.image_url %>/></a>
            <div class="descri-long">
              <a href="/furnitures/<%= furniture.id %>"><button style="margin-right: 5px; margin-left: -5px;" type="button" class="btn-group btn-group-xs btn-wishlist">View Details</button></a>
                <%= button_to "Save to Wishlist", add_wishlist_path, method: :post, class: "btn-group btn-group-xs btn-wishlist", params: { furniture_id: furniture.id, user_id: session[:user_id] } %>
            </div> 
          </div><!-- furni-img -->
          <div class="descri-short">
            <b>item:</b> <%= furniture.name %><br>
            <b>condition:</b> <%= furniture.condition %><br>
            <b>dimensions:</b> <%= furniture.dimensions %><br>
            <b>cost:</b> <%= furniture.furnipoints %> furnipts<br>
            <p class="trade-buy" style="margin-top:10px">
              <button type="button" class="btn btn-default btn-md openmodal" data-toggle="modal" data-target="#myModal" data-id="<%= furniture.furnipoints %>, <%= furniture.id %>">Buy</button>
              <button type="button" class="btn btn-default btn-md openmodal2" data-toggle="modal" data-target="#myModalTrade" data-id="<%= furniture.furnipoints %>, <%= furniture.id %>">Trade</button>
            </p>
          </div><!-- descri-short -->
        </div><!-- furni-line1 -->

        <div class="furni-links-index">
          <% if session[:user_id] == furniture.user_id %>
          <%= link_to 'Edit', edit_furniture_path(furniture) %> | <%= link_to "Delete", furniture, method: :delete, data: {confirm: "Are you sure?"}, id: 'delete' %> 
          <% end %>
        </div><!-- furni-links-index -->
      </div><!-- furni-obj -->

        <% end %>

</div><!-- filtered-furni --> </div>

app/views/furnitures/edit.html.erb
<h1>Editing Furniture</h1>

<%= render 'form' %>

<%= link_to 'Show', @furniture %> |
<%= link_to 'Back', furnitures_path %>

app/views/furnitures/index-staging.html.erb
          Furni: <% @furni.comments.each do |comment| %>
        <%= comment.content %>
        <% end %>

  <table class="table striped-table">
    <thead>
      <tr>
        <th>Item</th>
        <th>Description</th>
        <th>Photo</th>
        <th>Condition</th>
        <th>Dimensions in cm(height, width)</th>
        <th>Furnipoints</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @furnitures.each do |furniture| %>
        <tr>
          <td><%= furniture.name %></td>
          <td><%= furniture.content %></td>
          <td><img src=<%= furniture.image_url %>/></td>
          <td><%= furniture.condition %></td>
          <td><%= furniture.dimensions %></td>
          <td><%= link_to 'Show', furniture %></td>
          <td><%= link_to 'Edit', edit_furniture_path(furniture) %></td>
          <td><%= link_to 'Destroy', furniture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/furnitures/index.html.erb
<div class="container furni-container">
  <div class="furni-wrapper">
    <h2> Furniture for Sale in your Area </h2>
    <div class="filter">Filter By Type:
      <%= link_to "Beds", by_category_path(:type => "bed") %> | <%= link_to "Chairs", by_category_path(:type => "chair") %> | <%= link_to "Drawers", by_category_path(:type => "drawer") %> | <%= link_to "Desks", by_category_path(:type => "desk") %> | <%= link_to "Couches", by_category_path(:type => "couch") %> | <%= link_to "Tables", by_category_path(:type => "table") %>
    </div>

   <div class="new-furni"> <%= link_to 'Sell Your Furniture', new_furniture_path %> </div>

    <% @furnitures.each do |furniture| %>

        <div class="furni-obj">
          <div class="furni-line1">
          <div class="furni-img">
            <a class="owner" href="/users/<%=furniture.user_id %>">owned by <%=furniture.user.name %></a>
            <a style="width:200px; height: 200px" href="/furnitures/<%= furniture.id %>">
            <img style="width:200px; height: 200px" src=<%= furniture.image_url %>/></a>
            <div class="descri-long">
              <a href="/furnitures/<%= furniture.id %>"><button style="margin-right: 5px; margin-left: -5px;" type="button" class="btn-group btn-group-xs btn-wishlist">View Details</button></a>
                <%= button_to "Save to Wishlist", add_wishlist_path, method: :post, class: "btn-group btn-group-xs btn-wishlist", params: { furniture_id: furniture.id, user_id: session[:user_id] } %>
            </div> 
          </div><!-- furni-img -->
          <div class="descri-short">
            <b>item:</b> <%= furniture.name %><br>
            <b>condition:</b> <%= furniture.condition %><br>
            <b>dimensions:</b> <%= furniture.dimensions %><br>
            <b>cost:</b> <%= furniture.furnipoints %> furnipts<br>
            <p class="trade-buy" style="margin-top:10px">
              <button type="button" class="btn btn-default btn-md openmodal" data-toggle="modal" data-target="#myModalBuy" data-id="<%= furniture.furnipoints %>, <%= furniture.id %>">Buy</button>
              <button type="button" class="btn btn-default btn-md openmodal2" data-toggle="modal" data-target="#myModalTrade" data-id="<%= furniture.furnipoints %>, <%= furniture.id %>">Trade</button>
            </p>
          </div><!-- descri-short -->
        </div><!-- furni-line1 -->

        <div class="furni-links-index">
          <% if session[:user_id] == furniture.user_id %>
          <%= link_to 'Edit', edit_furniture_path(furniture) %> | <%= link_to "Delete", furniture, method: :delete, data: {confirm: "Are you sure?"}, id: 'delete' %> 
          <% end %>
        </div><!-- furni-links-index -->
      </div><!-- furni-obj -->

  <% end %>
  
  </div><!--furni-wrapper-->
  <br>


  <!-- ModalPurchase -->
  <div class="modal fade" id="myModalBuy" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Purchase this item</h4>
        </div>
        <div class="modal-body">
          This item costs 
            <input type="text" name="furniVal" id="furniVal" value="" readonly="readonly"/>
            furnipoints. Please select OK to confirm this purchase.  
            
            <% if current_user %>
              <form method="post" action="/purchase" class="purchase-form" data-remote="true">
                <input type="hidden" name="furniId" id="furniId" value=""/>
                <div><input class="btn btn-success ok-btn" value="OK" type="submit" /></div>
              </form>
            <% else %>
             <div class="login-plz-modal">Please login or signup to continue this purchase.</div>
           <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div><!--modal-footer-->
      </div>
      
    </div>
  </div>

  <!-- ModalTrade -->
  <div class="modal fade" id="myModalTrade" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Trade this item</h4>
        </div>
        <div class="modal-body" style="text-align:center">
          Do you wish to trade this item for one of yours? </br>
          If so, please choose from your list of available items: 
          </br>
          <% if current_user %>
          <form method="post" action="/trade" class="trade-form" data-remote="true">
            <input type="hidden" name="furniId2" id="furniId2" value=""/>
            <div class="furni-imgs">
                <% @current_furni.each do |furni| %>
                <input type="radio" name="furnichosen" value="<%= furni.id %>"> <img style="width:100px; height: 100px" src=<%= furni.image_url %>/>
                <% end %>
            </div>
            <input type="submit" value="OK" class="btn btn-success ok-btn-radio">
          </form>
          <% else %>
            <div class="login-plz-modal">Please login or signup to continue this trade.</div>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div><!--modal-footer-->
      </div>
      
    </div>
  </div>  


</div><!--container-->


<script>
$(document).on("click", ".openmodal", function () {
  console.log('purchase was clicked');
     var myModalData = $(this).data('id');
     console.log(myModalData);
     var myModalDataArr = myModalData.split(',')
     $(".modal-body #furniVal").val( myModalDataArr[0] );
     $(".modal-body form #furniId").val( myModalDataArr[1] );
});
$(document).on("click", ".openmodal2", function () {
  console.log('trade was clicked');
     var myModalData = $(this).data('id');
     console.log(myModalData);
     var myModalDataArr = myModalData.split(',')
     $(".modal-body form #furniId2").val( myModalDataArr[1] );
});
</script>

app/views/furnitures/new.html.erb
<h1>Add your Furniture</h1>

<% if session[:user_id] %>

<%= render 'form' %>

<% else %>

<div class="log-first">
	Sorry! You must log in or sign up before posting your furniture.
</div>

<% end %>

<%= link_to 'Back', furnitures_path %>

app/views/furnitures/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="furni-show">

    <div class="furni-top">
      <div class="furni-name"><h2><%= @furniture.name %></h2></div>


        <a href="/furnitures"><button class="btn btn-warning back-btn2">Back to furniture list</button></a>

            <div class="furni-links" style="margin-left: 60%">
              <% if session[:user_id] == @furniture.user_id %>
              <%= link_to 'Edit', edit_furniture_path(@furniture) %> | <%= link_to "Delete", @furniture, method: :delete, data: {confirm: "Are you sure?"}, id: 'delete' %> 
              <% end %>
            </div>        
      </div>
    

    <div class="furni-middle">

      <div class="furni-img">
        <img src=<%= @furniture.image_url %>/>
          <!-- <p class="trade-buy" style="margin-top:10px">
            <button type="button" class="btn btn-default btn-md openmodal" data-toggle="modal" data-target="#myModalPurchase" data-id="<%= @furniture.furnipoints %>, <%= @furniture.id %>">Buy</button>
            <button type="button" class="btn btn-default btn-md openmodal2" data-toggle="modal" data-target="#myModalExchange" data-id="<%= @furniture.furnipoints %>, <%= @furniture.id %>">Trade</button>
          </p> -->
          <a style="float: left; margin-top: 10px; margin-left: 5px;" class="owner" href="/users/<%=@furniture.user_id %>">owned by <%=@furniture.user.name %></a>
      </div>


      <div class="furni-descri">
        <p>
          <strong>Condition:</strong>
          <%= @furniture.condition %>
        </p>

        <p>
          <strong>Cost:</strong>
          <%= @furniture.furnipoints %> furnipoints
        </p>

        <p>
          <strong>Dimensions:</strong>
          <%= @furniture.dimensions %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @furniture.content %>
        </p>

        <hr size="3">

        <%= render "comments/newcomments" %>
 
      </div> <!-- furni-descri -->

    </div> <!--furni-middle -->

    <div class="furni-bottom">
        <%= render "comments/allcomments" %>
    </div>

  </div> <!-- furni show -->
</div> <!-- container -->


  <!-- ModalPurchase -->
  <div class="modal fade" id="myModalPurchase" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Purchase this item</h4>
        </div><!-- modal header-->
        <div class="modal-body">
          This item costs 
            <input type="text" name="furniVal" id="furniVal" value="" readonly="readonly"/>
            furnipoints. Please select OK to confirm this purchase.  
            
            <% if current_user %>
              <form method="post" action="/purchase" class="purchase-form" data-remote="true">
                <input type="hidden" name="furniId" id="furniId" value=""/>
                <div><input class="btn btn-success ok-btn" value="OK" type="submit" /></div>
              </form>
            <% else %>
             <div class="login-plz-modal">Please login or signup to continue this purchase.</div>
           <% end %>
        </div><!-- modal body-->
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div><!--modal-footer-->
      </div><!-- modal content-->
      
    </div><!-- modal dialog-->

  </div><!-- modal purchases-->



<script>
$(document).on("click", ".openmodal", function () {
  console.log('purchase was clicked');
     var myModalData = $(this).data('id');
     console.log(myModalData);
     var myModalDataArr = myModalData.split(',')
     $(".modal-body #furniVal").val( myModalDataArr[0] );
     $(".modal-body form #furniId").val( myModalDataArr[1] );
});
$(document).on("click", ".openmodal2", function () {
  console.log('trade was clicked');
     var myModalData = $(this).data('id');
     console.log(myModalData);
     var myModalDataArr = myModalData.split(',')
     $(".modal-body form #furniId2").val( myModalDataArr[1] );
});
</script>